#!/usr/bin/env gawk -f

BEGIN {
	for (i = 1; i < ARGC; i++) {
		#print "arg", i ":", ARGV[i]
		f = ARGV[i]
		if (f ~ /^[0-9]+/) {
			fld[f]++
		} else {
			fnd[f]++
		}
		delete ARGV[i]
	}

	#for (i in fld) { print "got", i }
	#for (i in fnd) { print "looking for", i }
	FS = "\t *"
}

#{ print "checking", $2, "[" $3 "]" }
$1 == 0 && fnd[$3]	{ fld[$2+0]++ }
$1 == 0 && skiphead	{ next }
fld[$2+0]		{ print }
